name: envexp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pipdeptree # pipdeptree may break if pip's internal API changes in newer releases
  - pip:
      - -e . # Install the package in the current directory
