name: experiment
channels:
  - conda-forge
dependencies:
  - python>=3.10.0,<3.11.0
  - numpy>=1.16.5,<2.0 # tensorflow compiled with numpy 1.x
  - h5py
  - protobuf <3.20.0
  - certifi
  - importlib-metadata
  - six
  - typing-extensions
  - zipp
  - pip
  - pip:
    - tensorflow==2.9.2
    - -e . # Install the package in the current directory