name: experiment
channels:
  - conda-forge
  - sleap-deps/label/dev
dependencies:
  - python=3.10
  - opencv
  - pyside6 >=6.4.1
  - protobuf <3.20,>=3.9.2
  - pip
  - pip:
      - -e . # Install the package in the current directory
