name: experiment
channels:
  - conda-forge
  - sleap-deps/label/dev
dependencies:
  - python=3.10
  - opencv >=4.10.0,<4.11
  - pyside6 >=6.4.1
  - pip
  - pip:
      - -e . # Install the package in the current directory
