name: experiment
channels:
  - conda-forge
  - sleap-deps/label/dev
dependencies:
  - python=3.10
  - opencv=4.5.5
  - pyside6=6.7.1
  - pip
  - pip:
      - -e . # Install the package in the current directory
